# you can use rvmm-config-gen to generate a config

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" 
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
arch = "arm64-v8a"

[Reddit-Extended]
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
arch = "arm64-v8a"

[Music-anddea]
enabled = true
app-name = "Music"
version = "auto"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
cli-source = "inotia00/revanced-cli"
cli-version = "v4.6.2"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"

[YouTube-anddea]
enabled = true
app-name = "YouTube"
version = "auto"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
cli-version = "v4.6.2"
rv-brand = "anddea"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" 
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Twitter-piko]
app-name = "Twitter"
build-mode = "apk"
version = "latest"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
cli-source = "inotia00/revanced-cli"
cli-version = "v4.6.2"
rv-brand = "piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Photos]
app-name = "Photos"
version = "latest"
build-mode = "apk"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"

[Twitter]
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
# arch = "arm64-v8a"

[TikTok]
version = "latest"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
# arch = "arm64-v8a"

# -------------

[YouTube]
build-mode = "apk"
excluded-patches = ""
included-patches = ""
version = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" 
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"

[Twitch]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
arch = "arm64-v8a"

[Reddit]
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
arch = "arm64-v8a"

[Messenger]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm64-v8a"

[Facebook]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
# arch = "armeabi-v7a"

[Spotify]
app_name = "Spotify"
build-mode = "apk"
version = "8.9.96.476"
included-patches = "'Hex'"
cli-source = "inotia00/revanced-cli"
cli-version = "v4.6.2"
patches-version = "v4.18.0-dev.5"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
direct-dlurl = "https://archive.org/download/com.spotify.music.rv"
arch = "all"

[Spotify-Lite]
enabled = true
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://spotify-lite.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
arch = "arm64-v8a"

[Backdrops]
enabled = false
version = "auto"
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[MyExpenses]
enabled = true
version = "auto"
uptodown-dlurl = "https://my-expenses.en.uptodown.com/android"

[NyxMusicPlayer]
enabled = true
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://nyx-music-player.en.uptodown.com/android"
arch = "both"

[IconPackStudio]
enabled = true
version = "auto"
uptodown-dlurl = "https://icon-pack-studio.en.uptodown.com/android"

[TickTick]
enabled = true
version = "auto"
uptodown-dlurl = "https://ticktick.en.uptodown.com/android"
arch = "both"

[Tasker]
enabled = true
uptodown-dlurl = "https://tasker.en.uptodown.com/android"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"

[Instagram]
app_name = "Instagram"
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"
#arch = "both"

[InShorts]
enabled = true
version = "auto"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
arch = "both"

[SyncForReddit]
enabled = false
version = "auto"
uptodown-dlurl = "https://sync-for-reddit.en.uptodown.com/android"

[InfinityForReddit]
enabled = true
version = "auto"
uptodown-dlurl = "https://infinity-for-reddit.en.uptodown.com/android"

[VSCO]
enabled = true
version = "auto"
uptodown-dlurl = "https://vsco-cam.en.uptodown.com/android"
arch = "both"

[Pixiv]
enabled = true
version = "auto"
uptodown-dlurl = "https://pixiv.en.uptodown.com/android"

[Trakt]
enabled = false
version = "auto"
# uptodown-dlurl = "https://trakt.en.uptodown.com/android"

[MemeGenerator]
enabled = true
version = "auto"
uptodown-dlurl = "https://meme-generator-free.en.uptodown.com/android"

[Lightroom]
enabled = true
version = "auto"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
arch = "both"

[Tumblr]
enabled = true
version = "auto"
uptodown-dlurl = "https://tumblr.en.uptodown.com/android"
